name: canopen_inventus_ci

on:
  push:
  pull_request:

jobs:
  canopen_inventus_osrf_industrial_ci:
    name: Jazzy OSRF Industrial
    strategy:
      matrix:
        env:
          - {ROS_REPO: testing, ROS_DISTRO: jazzy }
          - {ROS_REPO: main, ROS_DISTRO: jazzy}
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
  canopen_inventus_src_ci:
    name: Jazzy Source
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          package-name: |
            canopen_inventus_driver
            canopen_inventus_interfaces
